/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms.admin;

import DTO.User;
import Forms.LoginForm;
import java.awt.Cursor;

/**
 *
 * @author Farah Z
 */
public class adminMainForm extends javax.swing.JFrame {
    
     User logged = null;
    /**
     * Creates new form adminMainForm
     */
    public adminMainForm(User u) {
        initComponents();
        logged = u;
        this.greeting.setText(this.greeting.getText()+" "+u.getUsername());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        greeting = new javax.swing.JLabel();
        studentsBtn = new javax.swing.JLabel();
        studentsImg = new javax.swing.JLabel();
        instructorImg = new javax.swing.JLabel();
        instructorsBtn = new javax.swing.JLabel();
        classesImg = new javax.swing.JLabel();
        classesBtn = new javax.swing.JLabel();
        coursesImg = new javax.swing.JLabel();
        coursesBtn = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        studentitem = new javax.swing.JMenuItem();
        instructorItem = new javax.swing.JMenuItem();
        classesItem = new javax.swing.JMenuItem();
        coursesItm = new javax.swing.JMenuItem();
        admin = new javax.swing.JMenuItem();
        logout = new javax.swing.JMenu();

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(249, 226, 132));

        greeting.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        greeting.setIcon(new javax.swing.ImageIcon("C:\\Users\\Farah Z\\Desktop\\courses\\Third year 2020_2021\\OOP2\\Project\\SISProject\\src\\Assests\\business-icon-png-1934.png")); // NOI18N
        greeting.setText("Welcome ");

        studentsBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        studentsBtn.setText("Students ");
        studentsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studentsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentsBtnMouseClicked(evt);
            }
        });

        studentsImg.setIcon(new javax.swing.ImageIcon("C:\\Users\\Farah Z\\Desktop\\courses\\Third year 2020_2021\\OOP2\\Project\\SISProject\\src\\Assests\\person-icon-1671.png")); // NOI18N
        studentsImg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studentsImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentsImgMouseClicked(evt);
            }
        });

        instructorImg.setIcon(new javax.swing.ImageIcon("C:\\Users\\Farah Z\\Desktop\\courses\\Third year 2020_2021\\OOP2\\Project\\SISProject\\src\\Assests\\computer-user-icon-16381.png")); // NOI18N
        instructorImg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        instructorImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                instructorImgMouseClicked(evt);
            }
        });

        instructorsBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        instructorsBtn.setText("Instructors");
        instructorsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        instructorsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                instructorsBtnMouseClicked(evt);
            }
        });

        classesImg.setIcon(new javax.swing.ImageIcon("C:\\Users\\Farah Z\\Desktop\\courses\\Third year 2020_2021\\OOP2\\Project\\SISProject\\src\\Assests\\classroom-300x300.png")); // NOI18N
        classesImg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        classesImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                classesImgMouseClicked(evt);
            }
        });

        classesBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        classesBtn.setText("Classes");
        classesBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        classesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                classesBtnMouseClicked(evt);
            }
        });

        coursesImg.setIcon(new javax.swing.ImageIcon("C:\\Users\\Farah Z\\Desktop\\courses\\Third year 2020_2021\\OOP2\\Project\\SISProject\\src\\Assests\\book-icon-155.png")); // NOI18N
        coursesImg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        coursesImg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                coursesImgMouseClicked(evt);
            }
        });

        coursesBtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        coursesBtn.setText("Courses");
        coursesBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        coursesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                coursesBtnMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(139, 139, 139)
                .addComponent(studentsBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(instructorsBtn)
                .addGap(140, 140, 140))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(108, 108, 108)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(studentsImg)
                    .addComponent(coursesImg))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(classesImg)
                    .addComponent(instructorImg))
                .addGap(108, 108, 108))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(237, Short.MAX_VALUE)
                .addComponent(greeting, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(224, 224, 224))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(coursesBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(classesBtn)
                .addGap(135, 135, 135))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(greeting, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studentsImg)
                            .addComponent(instructorImg))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(studentsBtn)
                            .addComponent(instructorsBtn))
                        .addGap(94, 94, 94)
                        .addComponent(classesImg))
                    .addComponent(coursesImg))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classesBtn)
                    .addComponent(coursesBtn))
                .addContainerGap(85, Short.MAX_VALUE))
        );

        jMenu3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Farah Z\\Desktop\\courses\\Third year 2020_2021\\OOP2\\Project\\SISProject\\src\\Assests\\homepage-icon-png-2574.png")); // NOI18N
        jMenu3.setText("Home");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        studentitem.setText("Students");
        studentitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentitemActionPerformed(evt);
            }
        });
        jMenu3.add(studentitem);

        instructorItem.setText("instructors");
        instructorItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructorItemActionPerformed(evt);
            }
        });
        jMenu3.add(instructorItem);

        classesItem.setText("classes");
        classesItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                classesItemMouseClicked(evt);
            }
        });
        jMenu3.add(classesItem);

        coursesItm.setText("Courses");
        coursesItm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                coursesItmActionPerformed(evt);
            }
        });
        jMenu3.add(coursesItm);

        admin.setText("Administartors ");
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });
        jMenu3.add(admin);

        jMenuBar2.add(jMenu3);

        logout.setIcon(new javax.swing.ImageIcon("C:\\Users\\Farah Z\\Desktop\\courses\\Third year 2020_2021\\OOP2\\Project\\SISProject\\src\\Assests\\power_on-512.png")); // NOI18N
        logout.setText("LogOut");
        logout.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        logout.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutMouseClicked(evt);
            }
        });
        jMenuBar2.add(logout);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void studentsImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentsImgMouseClicked
        userManagerForm userForm = new userManagerForm(2,logged);
        userForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_studentsImgMouseClicked

    private void studentsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentsBtnMouseClicked
        userManagerForm userForm = new userManagerForm(2,logged);
        userForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_studentsBtnMouseClicked

    private void instructorImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instructorImgMouseClicked
        userManagerForm userForm = new userManagerForm(1,logged);
        userForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_instructorImgMouseClicked

    private void instructorsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_instructorsBtnMouseClicked
       userManagerForm userForm = new userManagerForm(1,logged);
        userForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_instructorsBtnMouseClicked

    private void classesImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_classesImgMouseClicked
        classesForm Frame = new classesForm(logged);
        Frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_classesImgMouseClicked

    private void classesBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_classesBtnMouseClicked
        classesForm Frame = new classesForm(logged);
        Frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_classesBtnMouseClicked

    private void logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutMouseClicked

        LoginForm login = new LoginForm();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutMouseClicked

    private void classesItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_classesItemMouseClicked
        classesForm Frame = new classesForm(logged);
        Frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_classesItemMouseClicked

    private void studentitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentitemActionPerformed
        userManagerForm userForm = new userManagerForm(2,logged);
        userForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_studentitemActionPerformed

    private void instructorItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructorItemActionPerformed
        userManagerForm userForm = new userManagerForm(1,logged);
        userForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_instructorItemActionPerformed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        userManagerForm userForm = new userManagerForm(0,logged);
        userForm.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_adminActionPerformed

    private void coursesImgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coursesImgMouseClicked
        CoursesForm Frame = new CoursesForm(logged);
        Frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_coursesImgMouseClicked

    private void coursesBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_coursesBtnMouseClicked
        CoursesForm Frame = new CoursesForm(logged);
        Frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_coursesBtnMouseClicked

    private void coursesItmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_coursesItmActionPerformed
        CoursesForm Frame = new CoursesForm(logged);
        Frame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_coursesItmActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminMainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
               // new adminMainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem admin;
    private javax.swing.JLabel classesBtn;
    private javax.swing.JLabel classesImg;
    private javax.swing.JMenuItem classesItem;
    private javax.swing.JLabel coursesBtn;
    private javax.swing.JLabel coursesImg;
    private javax.swing.JMenuItem coursesItm;
    private javax.swing.JLabel greeting;
    private javax.swing.JLabel instructorImg;
    private javax.swing.JMenuItem instructorItem;
    private javax.swing.JLabel instructorsBtn;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu logout;
    private javax.swing.JMenuItem studentitem;
    private javax.swing.JLabel studentsBtn;
    private javax.swing.JLabel studentsImg;
    // End of variables declaration//GEN-END:variables
}
