/*---
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms.admin;

import DTO.User;
import Repositories.userRepo;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Farah Z
 */
public class userManagerForm extends javax.swing.JFrame {

    /**
     * Creates new form userManagerForm
     */
    
    userRepo repo = new userRepo();
    User logged = null;
    int type ;
    
    
    public userManagerForm() {
        initComponents();
        
        // set background color of empty area of table
        ((DefaultTableCellRenderer)usersTable.getDefaultRenderer(Object.class))
                .setBackground(new Color (242,232,199));
        
        ((DefaultTableCellRenderer)usersTable.getDefaultRenderer(Object.class))
                      .setOpaque(false);

        this.jScrollPane1.getViewport().setOpaque(false);
        
        this.type= 0;
        this.logged= new User();
        logged.setType(0);
        logged.setUsername("admin");
        
        //setting the text to center inside the cell
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        usersTable.setDefaultRenderer(Object.class, centerRenderer);
       
       // change table header proporties, background and foreground colors, font , text alligment
       JTableHeader tHeader = usersTable.getTableHeader();
      // tHeader.setOpaque(false);
       
       
//        tHeader.setBackground(Color.BLUE);
       tHeader.setForeground(Color.BLUE);
       tHeader.setBackground(Color.BLACK);
       tHeader.setFont(new Font ("Times New Roman", Font.BOLD, 14));
       ((DefaultTableCellRenderer)tHeader.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);

      
        
        refreshTable(0);

    }
    
    public userManagerForm(int type, User u)
    {
         initComponents();
         this.logged= u;
         this.type = type;
         
         // set background color of empty area of table
        ((DefaultTableCellRenderer)usersTable.getDefaultRenderer(Object.class))
                .setBackground(new Color (242,232,199));
        
        ((DefaultTableCellRenderer)usersTable.getDefaultRenderer(Object.class))
                      .setOpaque(false);

        this.jScrollPane1.getViewport().setOpaque(false);
        
        
        //setting the text to center inside the cell
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
       usersTable.setDefaultRenderer(Object.class, centerRenderer);
       
       // change table header proporties, background and foreground colors, font , text alligment
       JTableHeader tHeader = usersTable.getTableHeader();
       tHeader.setBackground(new Color(156,107,22));
       tHeader.setForeground(new Color(0,0,0));
       tHeader.setFont(new Font ("Times New Roman", Font.BOLD, 14));
       ((DefaultTableCellRenderer)tHeader.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
      
        
        refreshTable(type);

    }
    
    public void refreshTable(int type)
    {
         DefaultTableModel modelPolygon = new DefaultTableModel(new Object[]
        {"id","First name","Last Name","Username", "Phone", "Email","password"},0);
        for ( User user : repo.getAllUsers(type))
        {
            modelPolygon.addRow(new Object[] {user.getID(),user.getFirstName(),user.getLastName(),
            user.getUsername(), user.getPhone(),user.getEmail(),user.getPassword() });
        }
       

             this.usersTable.setModel(modelPolygon);
             this.usersTable.getColumnModel().getColumn(0).setWidth(0);
             this.usersTable.getColumnModel().getColumn(0).setMinWidth(0);
             this.usersTable.getColumnModel().getColumn(0).setMaxWidth(0);
             
        //highlighting the selected type of users 
        switch (type)
        {
            case 0: adminLabel.setBackground( new Color(249,226,132));
            break;
            
            case 1: teacherLabel.setBackground( new Color(249,226,132));
            break;
            
            case 2: studentLabel.setBackground( new Color(249,226,132));
            break;
            default: break;
        }
           
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jPanel2 = new javax.swing.JPanel();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        usersTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        firstName = new javax.swing.JTextField();
        email = new javax.swing.JTextField();
        phone = new javax.swing.JTextField();
        lastName = new javax.swing.JTextField();
        removeBtn = new javax.swing.JButton();
        addBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        home = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        password = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        studentLabel = new javax.swing.JLabel();
        adminLabel = new javax.swing.JLabel();
        teacherLabel = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        refreshbtn = new javax.swing.JMenuItem();
        addMenu = new javax.swing.JMenuItem();
        removeMenu = new javax.swing.JMenuItem();
        updateUser = new javax.swing.JMenuItem();

        jPanel2.setBackground(new java.awt.Color(156, 107, 22));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 187, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(249, 226, 132));

        jScrollPane1.setBackground(new java.awt.Color(249, 226, 132));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        usersTable.setBackground(new java.awt.Color(249, 226, 132));
        usersTable.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        usersTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"1234", "1234", "1234", "1234"},
                {null, null, "1232", null},
                {null, null, "2312321", null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        usersTable.setGridColor(new java.awt.Color(204, 204, 204));
        usersTable.setName(""); // NOI18N
        usersTable.setOpaque(false);
        usersTable.setSelectionBackground(new java.awt.Color(156, 107, 22));
        usersTable.setSelectionForeground(new java.awt.Color(0, 0, 0));
        usersTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        usersTable.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        usersTable.setShowGrid(true);
        usersTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                usersTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(usersTable);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("First Name:");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Last Name:");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Email:");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel5.setText("Phone:");

        firstName.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        email.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        phone.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        lastName.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        removeBtn.setBackground(new java.awt.Color(225, 181, 70));
        removeBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Farah Z\\Desktop\\courses\\Third year 2020_2021\\OOP2\\Project\\SISProject\\src\\Assests\\remove-user-512.png")); // NOI18N
        removeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeBtnMouseClicked(evt);
            }
        });

        addBtn.setBackground(new java.awt.Color(225, 181, 70));
        addBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Farah Z\\Desktop\\courses\\Third year 2020_2021\\OOP2\\Project\\SISProject\\src\\Assests\\New_user_icon.png")); // NOI18N
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtnMouseClicked(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(225, 181, 70));
        updateBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Farah Z\\Desktop\\courses\\Third year 2020_2021\\OOP2\\Project\\SISProject\\src\\Assests\\check-tick-icon-14145.png")); // NOI18N
        updateBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                updateBtnMouseClicked(evt);
            }
        });

        home.setBackground(new java.awt.Color(225, 181, 70));
        home.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        home.setIcon(new javax.swing.ImageIcon("C:\\Users\\Farah Z\\Desktop\\courses\\Third year 2020_2021\\OOP2\\Project\\SISProject\\src\\Assests\\homepage-icon-png-2574.png")); // NOI18N
        home.setText("Back to home window");
        home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeMouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Password:");

        password.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addGap(18, 18, 18)
                            .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(removeBtn)
                            .addGap(40, 40, 40)
                            .addComponent(addBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(updateBtn))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(home)))
                .addGap(35, 35, 35))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(firstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(lastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(phone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(77, 77, 77)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(removeBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addBtn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(updateBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(28, 28, 28)
                .addComponent(home)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(156, 107, 22));

        studentLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        studentLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studentLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Farah Z\\Desktop\\courses\\Third year 2020_2021\\OOP2\\Project\\SISProject\\src\\Assests\\person-icon-small.png")); // NOI18N
        studentLabel.setText("Students         ");
        studentLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        studentLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentLabelMouseClicked(evt);
            }
        });

        adminLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        adminLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        adminLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Farah Z\\Desktop\\courses\\Third year 2020_2021\\OOP2\\Project\\SISProject\\src\\Assests\\business-icon-png-1934.png")); // NOI18N
        adminLabel.setText("Administrators");
        adminLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        adminLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminLabelMouseClicked(evt);
            }
        });

        teacherLabel.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        teacherLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        teacherLabel.setIcon(new javax.swing.ImageIcon("C:\\Users\\Farah Z\\Desktop\\courses\\Third year 2020_2021\\OOP2\\Project\\SISProject\\src\\Assests\\computer-user-small.png")); // NOI18N
        teacherLabel.setText("Instructrors     ");
        teacherLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        teacherLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                teacherLabelMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(studentLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(teacherLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(adminLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(adminLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(teacherLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(50, 50, 50)
                .addComponent(studentLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jMenu3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Farah Z\\Desktop\\courses\\Third year 2020_2021\\OOP2\\Project\\SISProject\\src\\Assests\\settings-icon-14968.png")); // NOI18N
        jMenu3.setText("Manage");
        jMenu3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        refreshbtn.setText("Refresh");
        refreshbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshbtnActionPerformed(evt);
            }
        });
        jMenu3.add(refreshbtn);

        addMenu.setText("Add User");
        addMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMenuActionPerformed(evt);
            }
        });
        jMenu3.add(addMenu);

        removeMenu.setText("Remove User");
        removeMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeMenuActionPerformed(evt);
            }
        });
        jMenu3.add(removeMenu);

        updateUser.setText("Update User");
        updateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateUserActionPerformed(evt);
            }
        });
        jMenu3.add(updateUser);

        jMenuBar2.add(jMenu3);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void removeBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeBtnMouseClicked
        
        int column = 3;
        int row = this.usersTable.getSelectedRow();
        if(row >= 0)
        {
            String username = this.usersTable.getValueAt(row, column).toString();
            int result = repo.deleteUser(logged, username );
            switch (result)
            {
                case 0:  JOptionPane.showMessageDialog(null,"User deleted successfuly");
                    return;
                case 1:  JOptionPane.showMessageDialog(null,"Error deleting please try again later");
                    return;
                case 3: JOptionPane.showMessageDialog(null,"the username you entered is not available in the database");
                    return;
                default: return;
            
            }  
        }
        
        
        refreshTable(type);
    }//GEN-LAST:event_removeBtnMouseClicked

    private void addBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseClicked
        
        User userAdd = new User();
        userAdd.setFirstName(this.firstName.getText());
        userAdd.setLastName(this.lastName.getText());
        userAdd.setEmail(this.email.getText());
        userAdd.setPhone(this.phone.getText());
        userAdd.setPassword(this.password.getText());
        userAdd.setType(type);
        
        int result = repo.addUser(logged, userAdd);
        
        switch (result)
            {
                case 0:  JOptionPane.showMessageDialog(null,"User added successfuly");
                    refreshTable(type);
                    break;     
                case 1:  JOptionPane.showMessageDialog(null,"Error creating user please try again later");
                    break;
                case 2: JOptionPane.showMessageDialog(null,"the user type you entered is not valid");
                    break;
                case 3: JOptionPane.showMessageDialog(null,"you don't have enough privilages");
                   break;
                default: break;
            
            }
          refreshTable(type);
    }//GEN-LAST:event_addBtnMouseClicked

    private void updateBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_updateBtnMouseClicked
        
        User userUpdate = new User();
       userUpdate.setFirstName(this.firstName.getText());
        userUpdate.setLastName(this.lastName.getText());
        userUpdate.setEmail(this.email.getText());
        userUpdate.setPhone(this.phone.getText());
        userUpdate.setPassword(this.password.getText());
        userUpdate.setType(type);
        
        int result = repo.updateUser(logged, userUpdate);
        
        switch (result)
            {
                case 0:  JOptionPane.showMessageDialog(null,"User updated successfuly");
                    refreshTable(type);
                    break;     
                case 1:  JOptionPane.showMessageDialog(null,"Error updating user please try again later");
                    break;
                case 2: JOptionPane.showMessageDialog(null,"the user type you entered is not valid");
                    break;
                case 3: JOptionPane.showMessageDialog(null,"you don't have enough privilages");
                   break;
                default: break;
            
            }
          refreshTable(type);
    }//GEN-LAST:event_updateBtnMouseClicked

    private void homeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeMouseClicked
        
        adminMainForm adminForm = new adminMainForm(logged);
        adminForm.setVisible(true);
        this.dispose();
        
        
    }//GEN-LAST:event_homeMouseClicked

    private void adminLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminLabelMouseClicked

        this.type= 0;
          refreshTable(type);
    }//GEN-LAST:event_adminLabelMouseClicked

    private void teacherLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_teacherLabelMouseClicked
        
        this.type=1;
          refreshTable(type);
    }//GEN-LAST:event_teacherLabelMouseClicked

    private void studentLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentLabelMouseClicked
        
        this.type=2;
          refreshTable(type);
    }//GEN-LAST:event_studentLabelMouseClicked

    private void addMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMenuActionPerformed
        User userAdd = new User();
        userAdd.setFirstName(this.firstName.getText());
        userAdd.setLastName(this.lastName.getText());
        userAdd.setEmail(this.email.getText());
        userAdd.setPhone(this.phone.getText());
        userAdd.setPassword(this.password.getText());
        userAdd.setType(type);

        
        int result = repo.addUser(logged, userAdd);
        
        switch (result)
            {
                case 0:  JOptionPane.showMessageDialog(null,"User added successfuly");
                    refreshTable(type);
                    break;     
                case 1:  JOptionPane.showMessageDialog(null,"Error creating user please try again later");
                    break;
                case 2: JOptionPane.showMessageDialog(null,"the user type you entered is not valid");
                    break;
                case 3: JOptionPane.showMessageDialog(null,"you don't have enough privilages");
                    break;
                default: return;
            
            }
        
          refreshTable(type);
    }//GEN-LAST:event_addMenuActionPerformed

    private void removeMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeMenuActionPerformed

        int column = 3;
        int row = this.usersTable.getSelectedRow();
        if(row >= 0)
        {
            String username = this.usersTable.getValueAt(row, column).toString();
            int result = repo.deleteUser(logged, username );
            switch (result)
            {
                case 0:  JOptionPane.showMessageDialog(null,"User deleted successfuly");
                    break;
                case 1:  JOptionPane.showMessageDialog(null,"Error deleting please try again later");
                    break;
                case 3: JOptionPane.showMessageDialog(null,"the username you entered is not available in the database");
                    break;
                default: return;
            
            }
            
              refreshTable(type);
        }
    }//GEN-LAST:event_removeMenuActionPerformed

    private void updateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateUserActionPerformed
        
         User userUpdate = new User();
       userUpdate.setFirstName(this.firstName.getText());
        userUpdate.setLastName(this.lastName.getText());
        userUpdate.setEmail(this.email.getText());
        userUpdate.setPhone(this.phone.getText());
        userUpdate.setPassword(this.password.getText());
        userUpdate.setType(type);
        
        int result = repo.updateUser(logged, userUpdate);
        
        switch (result)
            {
                case 0:  JOptionPane.showMessageDialog(null,"User updated successfuly");
                    refreshTable(type);
                    break;     
                case 1:  JOptionPane.showMessageDialog(null,"Error updating user please try again later");
                    break;
                case 2: JOptionPane.showMessageDialog(null,"the user type you entered is not valid");
                    break;
                case 3: JOptionPane.showMessageDialog(null,"you don't have enough privilages");
                   break;
                default: break;
            
            }
          refreshTable(type);
    }//GEN-LAST:event_updateUserActionPerformed

    private void usersTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_usersTableMouseClicked
     
      
        int column = 0;
        int row= this.usersTable.getSelectedRow();
        if(row>=0)
        {
            this.firstName.setText(this.usersTable.getValueAt(row, 1).toString());
            this.lastName.setText(this.usersTable.getValueAt(row,2).toString());
            this.phone.setText(this.usersTable.getValueAt(row, 4).toString());
            this.email.setText(this.usersTable.getValueAt(row,5).toString());
            this.password.setText(this.usersTable.getValueAt(row,7).toString());
        }
        
        
    }//GEN-LAST:event_usersTableMouseClicked

    private void refreshbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshbtnActionPerformed

        refreshTable(type);
    }//GEN-LAST:event_refreshbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(userManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(userManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(userManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(userManagerForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new userManagerForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JMenuItem addMenu;
    private javax.swing.JLabel adminLabel;
    private javax.swing.JTextField email;
    private javax.swing.JTextField firstName;
    private javax.swing.JButton home;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lastName;
    private javax.swing.JTextField password;
    private javax.swing.JTextField phone;
    private javax.swing.JMenuItem refreshbtn;
    private javax.swing.JButton removeBtn;
    private javax.swing.JMenuItem removeMenu;
    private javax.swing.JLabel studentLabel;
    private javax.swing.JLabel teacherLabel;
    private javax.swing.JButton updateBtn;
    private javax.swing.JMenuItem updateUser;
    private javax.swing.JTable usersTable;
    // End of variables declaration//GEN-END:variables
}
