/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms.Instructors;



import DTO.Course;
import DTO.User;
import Forms.LoginForm;
import Repositories.classRepo;
import Repositories.courseRepo;
import java.awt.Color;
import java.awt.Font;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

/**
 *
 * @author Farah Z
 */
public class instructorMainFrame extends javax.swing.JFrame {

    /**
     * Creates new form instructorMainFrame
     */
    User logged;
    courseRepo repo = new courseRepo();
    classRepo repoClass = new classRepo();
    
//    sectionReo
    //for testing purposes 
    
    public instructorMainFrame() {
        initComponents();
        initiateTable();
        logged = new User("ins12","helo@gmail.com","helo","world","03965472","P@ssw0rd",1);
       // username, String email, String firstname, String lastname, String phone, String password,String type
        RefreshTable();
    }
    
    public instructorMainFrame( User logged) {
        initComponents();
        initiateTable();
        this.logged = logged;
        this.greetings.setText(this.greetings.getText()+ logged.getFirstName());
        RefreshTable();
        
    }
    
    public void initiateTable()
    {
        // set background color of empty area of table
        ((DefaultTableCellRenderer)jTable1.getDefaultRenderer(Object.class))
                .setBackground(new Color (242,232,199));
        
        ((DefaultTableCellRenderer)jTable1.getDefaultRenderer(Object.class))
                      .setOpaque(false);

        this.jScrollPane1.getViewport().setOpaque(false);
        
        //setting the text to center inside the cell
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        jTable1.setDefaultRenderer(Object.class, centerRenderer);
        
        // change table header proporties, background and foreground colors, font , text alligment
       JTableHeader tHeader = jTable1.getTableHeader();
       tHeader.setForeground(Color.BLACK);
       tHeader.setBackground(Color.BLACK);
       tHeader.setFont(new Font ("Times New Roman", Font.BOLD, 14));
       ((DefaultTableCellRenderer)tHeader.getDefaultRenderer()).setHorizontalAlignment(JLabel.CENTER);
    }
    
    public void RefreshTable()
    {
        DefaultTableModel modelTable = new DefaultTableModel(new Object[]
                {"id","name", "class","time"},0);
        for( Course c : repo.getAllCoursesByType(logged))
        {
            modelTable.addRow(new Object[] { c.getID(),c.getName(),repoClass.getClassByID(c.getClassID()).getName() , c.getTime()});
        }
        
        this.jTable1.setModel(modelTable);
        this.jTable1.getColumnModel().getColumn(0).setWidth(0);
        this.jTable1.getColumnModel().getColumn(0).setMinWidth(0);
        this.jTable1.getColumnModel().getColumn(0).setMaxWidth(0);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        assigmentBtn = new javax.swing.JButton();
        ExamsBtn = new javax.swing.JButton();
        greetings = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        homeBtn = new javax.swing.JMenu();
        refreshBtn = new javax.swing.JMenuItem();
        profileBtn = new javax.swing.JMenuItem();
        assigmentItem = new javax.swing.JMenuItem();
        examsItem = new javax.swing.JMenuItem();
        logoutBtn = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(249, 226, 132));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jScrollPane1.setViewportBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        jTable1.setBackground(new java.awt.Color(249, 226, 132));
        jTable1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.setSelectionBackground(new java.awt.Color(156, 107, 22));
        jScrollPane1.setViewportView(jTable1);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel1.setText("My courses:");

        assigmentBtn.setBackground(new java.awt.Color(225, 181, 70));
        assigmentBtn.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        assigmentBtn.setText("View assigments ");
        assigmentBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                assigmentBtnMouseClicked(evt);
            }
        });

        ExamsBtn.setBackground(new java.awt.Color(225, 181, 70));
        ExamsBtn.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        ExamsBtn.setText("View Exams");
        ExamsBtn.setToolTipText("");
        ExamsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExamsBtnMouseClicked(evt);
            }
        });

        greetings.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        greetings.setText("Welcome back: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 340, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(51, 51, 51)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(assigmentBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ExamsBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(172, 172, 172)
                        .addComponent(greetings)))
                .addContainerGap(70, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(greetings)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 139, Short.MAX_VALUE)
                        .addComponent(assigmentBtn)
                        .addGap(39, 39, 39)
                        .addComponent(ExamsBtn)
                        .addGap(175, 175, 175))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(63, Short.MAX_VALUE))))
        );

        homeBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Farah Z\\Desktop\\courses\\Third year 2020_2021\\OOP2\\Project\\SISProject\\src\\Assests\\homepage-icon-png-2574.png")); // NOI18N
        homeBtn.setText("Home");
        homeBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        refreshBtn.setText("Refresh");
        refreshBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refreshBtnActionPerformed(evt);
            }
        });
        homeBtn.add(refreshBtn);

        profileBtn.setText("View my profile");
        profileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                profileBtnActionPerformed(evt);
            }
        });
        homeBtn.add(profileBtn);

        assigmentItem.setText("View assigments ");
        assigmentItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                assigmentItemActionPerformed(evt);
            }
        });
        homeBtn.add(assigmentItem);

        examsItem.setText("View Exams");
        examsItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                examsItemActionPerformed(evt);
            }
        });
        homeBtn.add(examsItem);

        jMenuBar1.add(homeBtn);

        logoutBtn.setIcon(new javax.swing.ImageIcon("C:\\Users\\Farah Z\\Desktop\\courses\\Third year 2020_2021\\OOP2\\Project\\SISProject\\src\\Assests\\power_on-512.png")); // NOI18N
        logoutBtn.setText("LogOut");
        logoutBtn.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        logoutBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutBtnMouseClicked(evt);
            }
        });
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });
        jMenuBar1.add(logoutBtn);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExamsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExamsBtnMouseClicked
        int column = 0;
       int row = this.jTable1.getSelectedRow();
       if(row>=0)
       {
           int id = Integer.parseInt(this.jTable1.getValueAt(row, column).toString());
           if (logged.getType() == 1)
          {
              
           instructorExamForm examForm = new  instructorExamForm(repo.getCourseByID(id),logged);
           examForm.setVisible(true);
           this.dispose();
          }
           else 
           {
               studentExamForm examStd = new studentExamForm(repo.getCourseByID(id),logged);
               examStd.setVisible(true);
               this.dispose();
           }
           
       }
       else{
             JOptionPane.showMessageDialog(null,"Please select a course to view assignments");
       }
    }//GEN-LAST:event_ExamsBtnMouseClicked

    private void assigmentBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_assigmentBtnMouseClicked
       int column = 0;
       int row = this.jTable1.getSelectedRow();
       if(row>=0)
       {
           int id = Integer.parseInt(this.jTable1.getValueAt(row, column).toString());
           if (logged.getType() == 1)
          {
              
           assignmentsForm form = new assignmentsForm(logged,id);
           form.setVisible(true);
           this.dispose();
          }
           else 
           {
               assignmentsFormStd formStd = new assignmentsFormStd(logged,id);
               formStd.setVisible(true);
               this.dispose();
           }
           
       }
       else{
             JOptionPane.showMessageDialog(null,"Please select a course to view assignments");
       }
       
    }//GEN-LAST:event_assigmentBtnMouseClicked

    private void refreshBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refreshBtnActionPerformed
        this.RefreshTable();
    }//GEN-LAST:event_refreshBtnActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        LoginForm login = new LoginForm();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void profileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_profileBtnActionPerformed
        profileFrame frame = new profileFrame(logged);
        frame.setVisible(true);
    }//GEN-LAST:event_profileBtnActionPerformed

    private void assigmentItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_assigmentItemActionPerformed
               int column = 0;
       int row = this.jTable1.getSelectedRow();
       if(row>=0)
       {
           int id = Integer.parseInt(this.jTable1.getValueAt(row, column).toString());
           if (logged.getType() == 1)
          {
              
           assignmentsForm form = new assignmentsForm(logged,id);
           form.setVisible(true);
           this.dispose();
          }
           else 
           {
               assignmentsFormStd formStd = new assignmentsFormStd(logged,id);
               formStd.setVisible(true);
               this.dispose();
           }
           
       }
       else{
             JOptionPane.showMessageDialog(null,"Please select a course to view assignments");
       }
    }//GEN-LAST:event_assigmentItemActionPerformed

    private void examsItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_examsItemActionPerformed
         int column = 0;
       int row = this.jTable1.getSelectedRow();
       if(row>=0)
       {
           int id = Integer.parseInt(this.jTable1.getValueAt(row, column).toString());
           if (logged.getType() == 1)
          {
              
           instructorExamForm examForm = new  instructorExamForm(repo.getCourseByID(id),logged);
           examForm.setVisible(true);
           this.dispose();
          }
           else 
           {
                studentExamForm examStd = new studentExamForm(repo.getCourseByID(id),logged);
               examStd.setVisible(true);
               this.dispose();
           }
           
       }
       else{
             JOptionPane.showMessageDialog(null,"Please select a course to view assignments");
       }
    }//GEN-LAST:event_examsItemActionPerformed

    private void logoutBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutBtnMouseClicked
        LoginForm login = new LoginForm();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(instructorMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(instructorMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(instructorMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(instructorMainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new instructorMainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ExamsBtn;
    private javax.swing.JButton assigmentBtn;
    private javax.swing.JMenuItem assigmentItem;
    private javax.swing.JMenuItem examsItem;
    private javax.swing.JLabel greetings;
    private javax.swing.JMenu homeBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JMenu logoutBtn;
    private javax.swing.JMenuItem profileBtn;
    private javax.swing.JMenuItem refreshBtn;
    // End of variables declaration//GEN-END:variables
}
